/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package decorador.view;

/**
 *
 * @author isaul
 */
public class MenuBotonesComida extends javax.swing.JPanel {

    /**
     * Creates new form MenuBotonesComida
     */
    public MenuBotonesComida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBotones = new javax.swing.JPanel();
        botonCafeSimple = new javax.swing.JButton();
        botonCrema = new javax.swing.JButton();
        botonAzucar = new javax.swing.JButton();
        botonPizza = new javax.swing.JButton();
        botonQueso = new javax.swing.JButton();
        botonPepperoni = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        botonSalami = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelBotones.setBackground(new java.awt.Color(255, 255, 255));

        botonCafeSimple.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decorador/cafe.jpg"))); // NOI18N
        botonCafeSimple.setText("Boton Cafe Simple");
        botonCafeSimple.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        botonCafeSimple.setIconTextGap(3);
        botonCafeSimple.setMaximumSize(new java.awt.Dimension(214, 185));
        botonCafeSimple.setMinimumSize(new java.awt.Dimension(214, 185));
        botonCafeSimple.setPreferredSize(new java.awt.Dimension(214, 185));

        botonCrema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decorador/crema.jpg"))); // NOI18N
        botonCrema.setText("Boton Crema");

        botonAzucar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decorador/azucar.jpg"))); // NOI18N
        botonAzucar.setText("Boton Azucar");
        botonAzucar.setMaximumSize(new java.awt.Dimension(214, 185));
        botonAzucar.setMinimumSize(new java.awt.Dimension(214, 185));

        botonPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decorador/pizzasimple.jpg"))); // NOI18N
        botonPizza.setText("Boton Pizza Sencilla");
        botonPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPizzaActionPerformed(evt);
            }
        });

        botonQueso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decorador/queso.jpg"))); // NOI18N
        botonQueso.setText("Boton Queso");
        botonQueso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonQuesoActionPerformed(evt);
            }
        });

        botonPepperoni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decorador/Pepperoni.jpg"))); // NOI18N
        botonPepperoni.setText("Boton Pepperoni");
        botonPepperoni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPepperoniActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decorador/ensalada.jpg"))); // NOI18N
        jButton7.setText("Boton Ensalada Sencilla");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decorador/vinagreta.jpg"))); // NOI18N
        jButton8.setText("Boton Vinagreta");

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decorador/pollo.jpg"))); // NOI18N
        jButton9.setText("Boton Pollo");

        botonSalami.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decorador/Salami.jpg"))); // NOI18N
        botonSalami.setText("Boton Salami");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/decorador/mate.jpg"))); // NOI18N
        jButton2.setText("Boton Tomate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonPizza)
                    .addComponent(jButton7)
                    .addComponent(botonCafeSimple, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(botonQueso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCrema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonSalami)
                            .addComponent(jButton8))
                        .addGap(67, 67, 67)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelBotonesLayout.createSequentialGroup()
                                .addComponent(jButton9)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelBotonesLayout.createSequentialGroup()
                                .addComponent(botonPepperoni)
                                .addContainerGap(24, Short.MAX_VALUE))))
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addComponent(botonAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(botonAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonCafeSimple, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCrema, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPepperoni)
                    .addComponent(botonSalami)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonPizza)
                            .addComponent(botonQueso))))
                .addGap(37, 37, 37)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addGroup(panelBotonesLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)
                            .addComponent(jButton8))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPizzaActionPerformed

    private void botonQuesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonQuesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonQuesoActionPerformed

    private void botonPepperoniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPepperoniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonPepperoniActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAzucar;
    private javax.swing.JButton botonCafeSimple;
    private javax.swing.JButton botonCrema;
    private javax.swing.JButton botonPepperoni;
    private javax.swing.JButton botonPizza;
    private javax.swing.JButton botonQueso;
    private javax.swing.JButton botonSalami;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelBotones;
    // End of variables declaration//GEN-END:variables
}
